// Mocks generated by Mockito 5.0.10 from annotations
// in best_architecture_challenge/test/features/fetch_posts/data/repositories/fetch_posts_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:best_architecture_challenge/features/fetch_posts/data/datasources/fetch_posts_remote_data_source.dart'
    as _i2;
import 'package:best_architecture_challenge/features/fetch_posts/data/models/post_model.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [FetchPostsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchPostsRemoteDataSource extends _i1.Mock
    implements _i2.FetchPostsRemoteDataSource {
  MockFetchPostsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.PostModel>> fetchPosts() =>
      (super.noSuchMethod(Invocation.method(#fetchPosts, []),
              returnValue: Future<List<_i4.PostModel>>.value(<_i4.PostModel>[]))
          as _i3.Future<List<_i4.PostModel>>);
}
